export const USERNAME_MIN_LENGTH = 5;
export const USERNAME_MAX_LENGTH = 20;
export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 20;
export const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]+$/;
export const MOBILE_NUMBER_REGEX = /^[0-9]*$/;
export const EMAIL_MIN_LENGTH = 5;
export const EMAIL_MAX_LENGTH = 50;
export const MOBILE_NUMBER_MIN_LENGTH = 10;
export const MOBILE_NUMBER_MAX_LENGTH = 10;
export const USERNAME_REGEX = /^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]+$/;
export const USERNAME_ERROR_MESSAGE = 'Username is required';
export const PASSWORD_ERROR_MESSAGE = 'Password is required';
export const PASSWORD2_ERROR_MESSAGE = 'Confirm password is required';
export const EMAIL_ERROR_MESSAGE = 'Email is required';
export const MOBILE_NUMBER_ERROR_MESSAGE = 'Mobile number is required';
export const PASSWORD_MIN_LENGTH_ERROR_MESSAGE = 'Password must be at least 8 characters long';
export const PASSWORD_MAX_LENGTH_ERROR_MESSAGE = 'Password must be at most 20 characters long';
export const PASSWORD_REGEX_ERROR_MESSAGE =
  'Password must contain at least one letter lowercase, one letter uppercase, one number and one special character';
export const MOBILE_NUMBER_MIN_LENGTH_ERROR_MESSAGE = 'Mobile number must be at least 10 characters long';
export const MOBILE_NUMBER_MAX_LENGTH_ERROR_MESSAGE = 'Mobile number must be at most 10 characters long';
export const MOBILE_NUMBER_REGEX_ERROR_MESSAGE = 'Mobile number must contain only numbers';
export const EMAIL_MIN_LENGTH_ERROR_MESSAGE = 'Email must be at least 5 characters long';
export const EMAIL_MAX_LENGTH_ERROR_MESSAGE = 'Email must be at most 50 characters long';
export const EMAIL_REGEX_ERROR_MESSAGE = 'Email must be a valid email address';
export const USERNAME_MIN_LENGTH_ERROR_MESSAGE = 'Username must be at least 5 characters long';
export const USERNAME_MAX_LENGTH_ERROR_MESSAGE = 'Username must be at most 20 characters long';
export const USERNAME_REGEX_ERROR_MESSAGE = 'Username must contain only alphabets and numbers';
export const PASSWORD2_NOT_MATCH_ERROR_MESSAGE = 'Passwords do not match';
