# Generated by Django 4.0.1 on 2022-04-30 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='2022-04-30', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('word', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=100)),
                ('example', models.CharField(max_length=200)),
                ('phonetic', models.CharField(max_length=100)),
                ('audio', models.CharField(max_length=100)),
                ('pos', models.CharField(choices=[('Noun', 'noun'), ('Verb', 'verb'), ('Adjective', 'adjective'), ('Adverb', 'adverb'), ('Pronoun', 'pronoun'), ('Conjunction', 'conjunction'), ('Determiner', 'determiner'), ('Preposition', 'preposition'), ('Numeral', 'numeral'), ('Interjection', 'interjection'), ('Particle', 'particle'), ('Other', 'other')], default='Noun', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('fi', 'Finnish'), ('el', 'Greek'), ('hu', 'Hungarian'), ('is', 'Icelandic'), ('id', 'Indonesian'), ('ga', 'Irish'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt-br', 'Portuguese (Brazil)'), ('ro', 'Romanian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('cy', 'Welsh')], default='en', max_length=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='entities.collection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
