# Generated by Django 4.0.4 on 2022-05-01 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

	initial = True

	dependencies = [
		('entities', '0001_initial'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name='vocabulary',
			name='created_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='vocabulary',
			name='deleted_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='vocabulary',
			name='updated_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='collection',
			name='created_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='collection',
			name='deleted_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='collection',
			name='updated_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
		),
	]
