# Generated by Django 4.0.4 on 2022-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='pos',
            field=models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adj'), ('adverb', 'Adv'), ('pronoun', 'Pron'), ('conjunction', 'Conj'), ('determiner', 'Det'), ('preposition', 'Prep'), ('numeral', 'Num'), ('interjection', 'Interj'), ('particle', 'Prt'), ('other', 'X')], default='noun', max_length=50),
        ),
    ]
