# Generated by Django 4.0.4 on 2022-05-01 10:01

from django.db import migrations, models
import entities.models

class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Lesson',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('deleted_at', models.DateTimeField(blank=True, null=True)),
				('name', models.CharField(default=entities.models.now_to_string, max_length=50)),
				('description', models.CharField(blank=True, max_length=200, null=True)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name = 'LessonContent',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('deleted_at', models.DateTimeField(blank=True, null=True)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='LessonItem',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('deleted_at', models.DateTimeField(blank=True, null=True)),
				('typing_count', models.IntegerField(default=0)),
				('right_count', models.IntegerField(default=0)),
				('wrong_list', models.CharField(blank=True, max_length=200, null=True)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='Quiz',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('deleted_at', models.DateTimeField(blank=True, null=True)),
				('question', models.CharField(blank=True, max_length=200, null=True)),
				('answer1', models.CharField(blank=True, max_length=50, null=True)),
				('answer2', models.CharField(blank=True, max_length=50, null=True)),
				('answer3', models.CharField(blank=True, max_length=50, null=True)),
				('correct_answer', models.CharField(blank=True, max_length=50, null=True)),
				('question_type', models.CharField(choices=[('fm', 'Find Meaning'), ('fw', 'Find Word')], default='fm', max_length=50)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='QuizContent',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('deleted_at', models.DateTimeField(blank=True, null=True)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='Test',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('deleted_at', models.DateTimeField(blank=True, null=True)),
				('name', models.CharField(default='20220501', max_length=50)),
				('description', models.CharField(blank=True, max_length=200, null=True)),
			],
			options={
				'abstract': False,
			},
		),
	]
