# Generated by Django 4.0.4 on 2022-05-01 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

	initial = True

	dependencies = [
		('study', '0001_initial'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('entities', '0002_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='test',
			name='created_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='test',
			name='deleted_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='test',
			name='updated_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='quizcontent',
			name='created_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='quizcontent',
			name='deleted_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='quizcontent',
			name='quiz',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_content', to='study.quiz'),
		),
		migrations.AddField(
			model_name='quizcontent',
			name='test',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_content', to='study.test'),
		),
		migrations.AddField(
			model_name='quizcontent',
			name='updated_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='quiz',
			name='created_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='quiz',
			name='deleted_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='quiz',
			name='updated_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='quiz',
			name='vocabulary',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.vocabulary'),
		),
		migrations.AddField(
			model_name='lessonitem',
			name='created_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='lessonitem',
			name='deleted_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='lessonitem',
			name='updated_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='lessonitem',
			name='vocabulary',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.vocabulary'),
		),
		migrations.AddField(
			model_name='lessoncontent',
			name='created_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='lessoncontent',
			name='deleted_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='lessoncontent',
			name='item',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_content', to='study.lessonitem'),
		),
		migrations.AddField(
			model_name='lessoncontent',
			name='lesson',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_content', to='study.lesson'),
		),
		migrations.AddField(
			model_name='lessoncontent',
			name='updated_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='lesson',
			name='created_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='lesson',
			name='deleted_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='lesson',
			name='updated_by',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
		),
	]
